.TH SAIJ 1  Linux 

.SH NAME
SAIJ \- Squelette Assembler In Java, permet d'asembler un programme pour la machine squelette
.SH SYNOPSIS
.B saij fichier [-o nom] [-version_proc] [-R]
.SH DESCRIPTION
permet d'assembler un fichier en binaire pour l'executer sur machine squelette.

.SH OPTIONS

.IP -o nom
le fichier a assembler

.IP -version_proc
la version du processeur squelette qui executera le code (B1 par défault)

.IP -R
indique que le fichier sera à placer dans une mémoire à lecture seule

.SH AUTEUR
Fabien ANXA
